apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: simple-node-app
  name: simple-node-app
spec:
  ports:
  - name: 8080-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: simple-node-app
  type: ClusterIP
status:
  loadBalancer: {}
