apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: simple-node-app
  name: simple-node-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-node-app
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: simple-node-app
    spec:
      containers:
      - image: namoo4u/simple-node-app
        name: simple-node-app
        resources: {}
status: {}
